Repository ppc64le-cloud/kubetest2-plugins, pull requests merged in 2024-11, with the labels that each got.

#176 DumpClusterLogs + IsUp implementation for kubetest2.
  kubetest2-tf/deployer/deployer.go
  kubetest2-tf/deployer/dumplogs.go
Labels: size/L, lgtm, approved

#179 Extend DumpClusterLogs with additional node level information
  kubetest2-tf/deployer/deployer.go
  kubetest2-tf/deployer/dumplogs.go
  pkg/providers/common/provider.go
Labels: size/M, lgtm, approved

#180 Refine DumpClusterLogs
  kubetest2-tf/deployer/dumplogs.go
  pkg/providers/common/provider.go
  pkg/providers/powervs/powervs.go
Labels: size/M, tide/merge-method-squash, lgtm, approved

#181 Initialize the CR logs command-pair during runtime
  kubetest2-tf/deployer/dumplogs.go
  pkg/providers/common/provider.go
Labels: size/S, lgtm, approved

#182 Move logs under artifacts
  kubetest2-tf/deployer/deployer.go
  kubetest2-tf/deployer/dumplogs.go
Labels: size/XS, lgtm, approved

#186 Include COS HMAC type of credential
  kubetest2-tf/deployer/deployer.go
  pkg/build/cos_hmac_credentials_provider.go
  pkg/build/options.go
  pkg/build/stage-ibmcos.go
Labels: size/L, lgtm, approved
