Repository ppc64le-cloud/kubetest2-plugins, pull requests merged in 2024-10, with the labels that each got.

#160 Add suport for --build
  go.mod
  go.sum
  kubetest2-tf/deployer/build.go
  kubetest2-tf/deployer/deployer.go
  kubetest2-tf/deployer/options/build.go
  pkg/build/build.go
  pkg/build/make.go
  pkg/build/options.go
  pkg/build/stage.go
Labels: lgtm, size/XXL, approved

#168 IBM COS Stage
  .gitignore
  go.mod
  go.sum
  kubetest2-tf/deployer/build.go
  pkg/build/options.go
  pkg/build/stage-ibmcos.go
Labels: size/L, lgtm, approved

#169 Phase 1: Refactor the flags and align with octago/sflags
  kubetest2-tf/deployer/deployer.go
Labels: size/M, lgtm, approved

#171 fix the SetKubeConfig flag
  kubetest2-tf/deployer/deployer.go
Labels: size/XS, lgtm, approved

#172 fix the set-kubeconfig flag typo
  kubetest2-tf/deployer/deployer.go
Labels: size/XS, lgtm, approved

#173 update the octago/sflags dependency
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#177 Add --stage to accept Directory input in cos bucket
  pkg/build/stage-ibmcos.go
Labels: size/XS, lgtm, approved
